"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/fBWZjEPuTpD
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import { Button } from "@/components/ui/button";
import React, { useState } from "react";
import Link from "next/link";
import {
  NavigationMenu,
  NavigationMenuItem,
  NavigationMenuList,
} from "@/components/ui/navigation-menu";
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
  SheetFooter,
  SheetClose,

} from "@/components/ui/sheet";
import { Label } from "@/components/ui/label"
import { HamburgerMenuIcon } from "@radix-ui/react-icons";


type RouteProps = {
  href: string;
  label: string;
};

const routeList: RouteProps[] = [
  {
    href: "/small-business",
    label: "SMALL BUSINESS",
  },
  {
    href: "/commercial",
    label: "COMMERCIAL",
  },
  {
    href: "/wealth",
    label: "WEALTH",
  },
];
export function RootNavbar() {
  const [isOpen, setIsOpen] = useState<Boolean>(false);

  return (
    <header className="sticky ">

      {/* Mobile nav */}
      <NavigationMenu className="mx-auto md:hidden border-b border-foreground">
        <NavigationMenuList className="container h-14 px-4 w-screen flex justify-between ">
          <NavigationMenuItem className="font-bold flex">
            <Link href="/" className="flex items-center space-x-4">
              <img
                src="/proxima.svg"
                alt="Logo"
                className="h-10"
                width="40"
                height="40"
                style={{ aspectRatio: "40/40", objectFit: "cover" }}
              />
              <h1 className="text-md font-bold text-foreground">
                Proxima Heritage Crest
              </h1>
            </Link>
          </NavigationMenuItem>


          <span className="flex md:hidden">

            <Sheet>
              <SheetTrigger asChild>
                <Button variant="outline">
                  <HamburgerMenuIcon />
                </Button>
              </SheetTrigger>
              <SheetContent>
                <SheetHeader>
                  <Link href="/" >
                    <img
                      src="/proxima.svg"
                      alt="Logo"
                      className="h-10"
                      width="100"
                      height="100"
                      style={{ aspectRatio: "40/40", objectFit: "cover" }}
                    />

                  </Link>
                </SheetHeader>
                <div className="grid gap-4 py-4">
                  {routeList.map(({ href, label }) => (
                    <Link href={href} className="grid items-center gap-4 p-2 border-b border-foreground" key={href}>
                      <h2 className="text-center text-foreground font-bold">
                        {label}
                      </h2>
                    </Link>
                  ))}
                </div>
                <SheetFooter className="pt-4">
                  <SheetClose asChild>
                    <Button type="submit">
                      <Link href={'/account'} >Account</Link>
                    </Button>
                  </SheetClose>
                </SheetFooter>
              </SheetContent>
            </Sheet>
          </span>

        </NavigationMenuList>
      </NavigationMenu>

      <nav className="hidden md:flex items-center justify-between p-4 border-b">
        <Link href="/" className="flex items-center space-x-4">
          <img
            src="/proxima.svg"
            alt="Logo"
            className="h-10"
            width="40"
            height="40"
            style={{ aspectRatio: "40/40", objectFit: "cover" }}
          />
          <h1 className="text-2xl font-bold text-foreground">
            Proxima Heritage Crest
          </h1>
        </Link>
        <nav className="flex items-center space-x-8 text-sm font-medium text-foreground">
          {routeList.map(({ href, label }) => (
            <React.Fragment key={href}>
              <Link href={href} className="text-gray-500">
                {label}
              </Link>
            </React.Fragment>
          ))}
        </nav>
        <div className="flex items-center space-x-4">
          <Link href={"/help"}>
            <MessageCircleQuestionIcon className="w-6 h-6 text-gray-500" />
          </Link>
          <Link href={"/login"}>
            <Button
              variant="outline"
              className="text-foreground border-foreground"
            >
              Account
            </Button>
          </Link>
        </div>
      </nav>

    </header>
  );
}

//@ts-ignore
function ChevronDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  );
}

//@ts-ignore
function MessageCircleQuestionIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M7.9 20A9 9 0 1 0 4 16.1L2 22Z" />
      <path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3" />
      <path d="M12 17h.01" />
    </svg>
  );
}
