/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/NgDKLt4Zd3e
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Arimo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from '@/components/ui/input';
import {
  Collapsible,
  CollapsibleTrigger,
  CollapsibleContent
} from '@/components/ui/collapsible';

export function Help() {
  return (
    <div className="mx-auto w-full max-w-4xl px-4 py-12 sm:px-6 lg:px-8">
      <div className="space-y-8">
        <div>
          <h1 className="text-3xl font-bold">Help & Support</h1>
          <p className="mt-2 text-muted-foreground">
            Find answers to your questions about the Proxima Heritage Crest
            banking app.
          </p>
          <div className="relative mt-6">
            <div className="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
              <SearchIcon className="h-5 w-5 text-muted-foreground" />
            </div>
            <Input
              type="search"
              placeholder="Search for help topics"
              className="block w-full rounded-md bg-muted py-2 pl-10 pr-4 text-foreground focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"
            />
          </div>
        </div>
        <div className="space-y-4">
          <Collapsible className="overflow-hidden rounded-md border">
            <CollapsibleTrigger className="flex items-center justify-between bg-muted px-4 py-3 text-lg font-medium [&[data-state=open]>svg]:rotate-90">
              Account Management
              <ChevronRightIcon className="h-5 w-5 transition-transform" />
            </CollapsibleTrigger>
            <CollapsibleContent className="space-y-2 px-4 py-3">
              <div>
                <h3 className="text-lg font-medium">
                  How do I update my personal information?
                </h3>
                <p className="text-muted-foreground">
                  To update your personal information, log into your Proxima
                  Heritage Crest account and navigate to the "Profile" section.
                  From there, you can update your name, address, phone number,
                  and other details.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium">
                  How do I change my password?
                </h3>
                <p className="text-muted-foreground">
                  To change your password, log into your Proxima Heritage Crest
                  account and navigate to the "Security" section. From there,
                  you can update your password.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium">
                  How do I close my account?
                </h3>
                <p className="text-muted-foreground">
                  To close your Proxima Heritage Crest account, please contact
                  our customer support team. They will guide you through the
                  process and ensure that your account is closed properly.
                </p>
              </div>
            </CollapsibleContent>
          </Collapsible>
          <Collapsible className="overflow-hidden rounded-md border">
            <CollapsibleTrigger className="flex items-center justify-between bg-muted px-4 py-3 text-lg font-medium [&[data-state=open]>svg]:rotate-90">
              Transactions
              <ChevronRightIcon className="h-5 w-5 transition-transform" />
            </CollapsibleTrigger>
            <CollapsibleContent className="space-y-2 px-4 py-3">
              <div>
                <h3 className="text-lg font-medium">
                  How do I view my transaction history?
                </h3>
                <p className="text-muted-foreground">
                  To view your transaction history, log into your Proxima
                  Heritage Crest account and navigate to the "Transactions"
                  section. From there, you can view and filter your past
                  transactions.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium">
                  How do I make a transfer?
                </h3>
                <p className="text-muted-foreground">
                  To make a transfer, log into your Proxima Heritage Crest
                  account and navigate to the "Transfers" section. From there,
                  you can select the account you want to transfer from, the
                  account you want to transfer to, and the amount you want to
                  transfer.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium">
                  How do I set up recurring payments?
                </h3>
                <p className="text-muted-foreground">
                  To set up recurring payments, log into your Proxima Heritage
                  Crest account and navigate to the "Payments" section. From
                  there, you can set up recurring payments for bills,
                  subscriptions, or other expenses.
                </p>
              </div>
            </CollapsibleContent>
          </Collapsible>
          <Collapsible className="overflow-hidden rounded-md border">
            <CollapsibleTrigger className="flex items-center justify-between bg-muted px-4 py-3 text-lg font-medium [&[data-state=open]>svg]:rotate-90">
              Security
              <ChevronRightIcon className="h-5 w-5 transition-transform" />
            </CollapsibleTrigger>
            <CollapsibleContent className="space-y-2 px-4 py-3">
              <div>
                <h3 className="text-lg font-medium">
                  How do I enable two-factor authentication?
                </h3>
                <p className="text-muted-foreground">
                  To enable two-factor authentication, log into your Proxima
                  Heritage Crest account and navigate to the "Security" section.
                  From there, you can enable two-factor authentication to add an
                  extra layer of security to your account.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium">
                  How do I report a lost or stolen card?
                </h3>
                <p className="text-muted-foreground">
                  To report a lost or stolen card, please contact our customer
                  support team immediately. They will be able to cancel your
                  card and issue a new one.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium">
                  How do I protect my account from fraud?
                </h3>
                <p className="text-muted-foreground">
                  To protect your Proxima Heritage Crest account from fraud, we
                  recommend enabling two-factor authentication, being cautious
                  of phishing attempts, and regularly reviewing your transaction
                  history.
                </p>
              </div>
            </CollapsibleContent>
          </Collapsible>
          <Collapsible className="overflow-hidden rounded-md border">
            <CollapsibleTrigger className="flex items-center justify-between bg-muted px-4 py-3 text-lg font-medium [&[data-state=open]>svg]:rotate-90">
              Loans
              <ChevronRightIcon className="h-5 w-5 transition-transform" />
            </CollapsibleTrigger>
            <CollapsibleContent className="space-y-2 px-4 py-3">
              <div>
                <h3 className="text-lg font-medium">
                  How do I apply for a loan?
                </h3>
                <p className="text-muted-foreground">
                  To apply for a loan, log into your Proxima Heritage Crest
                  account and navigate to the "Loans" section. From there, you
                  can start the application process.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium">
                  How do I check the status of my loan application?
                </h3>
                <p className="text-muted-foreground">
                  To check the status of your loan application, log into your
                  Proxima Heritage Crest account and navigate to the "Loans"
                  section. From there, you can view the status of your
                  application.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium">
                  How do I make a loan payment?
                </h3>
                <p className="text-muted-foreground">
                  To make a loan payment, log into your Proxima Heritage Crest
                  account and navigate to the "Loans" section. From there, you
                  can make a payment on your loan.
                </p>
              </div>
            </CollapsibleContent>
          </Collapsible>
        </div>
      </div>
    </div>
  );
}

function ChevronRightIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  );
}

function SearchIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  );
}
