/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/pUZBaYLksal
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import Link from 'next/link';

export function Terms() {
  return (
    <div className="py-6 md:py-12 lg:py-16">
      <div className="container px-4 md:px-6">
        <div className="prose mx-auto max-w-3xl">
          <div className="space-y-2">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl/none">
              Terms &amp; Conditions
            </h1>
            <p>
              Please read these terms and conditions carefully before using our
              website.
            </p>
          </div>
          <div className="space-y-8">
            <section>
              <h2 className="text-2xl font-bold tracking-tight">1. Terms</h2>
              <p>
                By accessing the website at
                <Link href="#" className="underline" prefetch={false}>
                  https://example.com
                </Link>
                , you are agreeing to be bound by these terms of service, all
                applicable laws and regulations, and agree that you are
                responsible for compliance with any applicable local laws. If
                you do not agree with any of these terms, you are prohibited
                from using or accessing this site. The materials contained in
                this website are protected by applicable copyright and trademark
                law.
              </p>
            </section>
            <section>
              <h2 className="text-2xl font-bold tracking-tight">
                2. Use License
              </h2>
              <p>
                Permission is granted to temporarily download one copy of the
                materials (information or software) on Example's website for
                personal, non-commercial transitory viewing only. This is the
                grant of a license, not a transfer of title, and under this
                license you may not:
              </p>
              <ul className="list-inside list-disc">
                <li>modify or copy the materials;</li>
                <li>
                  use the materials for any commercial purpose, or for any
                  public display (commercial or non-commercial);
                </li>
                <li>
                  attempt to decompile or reverse engineer any software
                  contained on Example's website;
                </li>
                <li>
                  remove any copyright or other proprietary notations from the
                  materials; or
                </li>
                <li>
                  transfer the materials to another person or "mirror" the
                  materials on any other server.
                </li>
              </ul>
            </section>
            <section>
              <h2 className="text-2xl font-bold tracking-tight">
                3. Disclaimer
              </h2>
              <p>
                The materials on Example's website are provided on an 'as is'
                basis. Example makes no warranties, expressed or implied, and
                hereby disclaims and negates all other warranties including,
                without limitation, implied warranties or conditions of
                merchantability, fitness for a particular purpose, or
                non-infringement of intellectual property or other violation of
                rights.
              </p>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
}
