'use client';
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/J1Lj8GJg4FV
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  CardFooter
} from '@/components/ui/card';
import { Label } from '@/components/ui/label';
import {
  Select,
  SelectTrigger,
  SelectValue,
  SelectContent,
  SelectItem
} from '@/components/ui/select';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { toast } from 'sonner';
import { withdrawFunds } from '@/actions/withdraw';

export function Withdraw() {
  const withdraw = () => {
    withdrawFunds().then((res: any) => {
      toast.error('Error', {
        description: res.error,
        position: 'bottom-center'
      });
    });
  };
  return (
    <Card className="w-full max-w-md">
      <CardHeader>
        <CardTitle>Withdraw Funds</CardTitle>
        <CardDescription>
          Select your bank account and enter the amount to withdraw.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="space-y-2">
          <Label htmlFor="account">Bank Account</Label>
          <Select>
            <SelectTrigger id="account">
              <SelectValue placeholder="Select account" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="checking">Checking Account</SelectItem>
              <SelectItem value="savings">Savings Account</SelectItem>
              <SelectItem value="business">Business Account</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <div className="space-y-2">
          <Label htmlFor="amount">Withdrawal Amount</Label>
          <Input id="amount" type="number" placeholder="Enter amount" />
        </div>
      </CardContent>
      <CardFooter>
        <Button className="ml-auto" onClick={withdraw}>
          Withdraw
        </Button>
      </CardFooter>
    </Card>
  );
}
